name: reviewdog
on: 
  pull_request: 
    types: [synchronize, opened]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
         
     - name: Setup Node.js
       uses: actions/setup-node@v2
       with:
         node-version: '^16.13.2'
         registry-url: 'https://npm.pkg.github.com'
    
     - name: Update Yarn
       run: yarn global add yarn

     - name: Install dependencies
       run: yarn install
       env:
         NODE_AUTH_TOKEN: ${{ secrets.NODE_GITHUB_TOKEN }}

     - uses: reviewdog/action-eslint@v1
       with:
         reporter: github-pr-review