import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import BackButton from '../../src/modules/core/components/BackButton/BackButton';
import Footer from '../../src/modules/core/components/Footer/Footer';
import Header from '../../src/modules/core/components/Header/Header';

const Terms = () => {
  return (
    <div>
      <Header />
      <div className="">
        <div className="fixed bg-brand-primary -z-20 h-screen w-screen top-0"></div>
        <div className="video-bg-adjustment absolute -z-[5] w-screen h-screen min-h-screen"></div>
        <div className="w-screen min-h-screen absolute -z-10 bg-brand-primary">
          <video
            className="w-screen object-cover min-h-screen opacity-50 bg-brand-primary"
            muted
            loop
            autoPlay
            playsInline={true}
          >
            <source src="./images/hero_video.mp4" />
          </video>
        </div>

        <div className="container mx-auto pt-[54px] px-4 sm:px-2">
          <BackButton path="Home - Termos de uso" />
          <h2 className="text-[#5a9dbf] font-roboto text-[47px] font-bold mt-[150px]">
            PRIMESEA NFT Terms of Use
          </h2>
          <p className="text-white font-roboto text-[20px] mt-[70px] ">
            <b>Welcome</b>
            <br />
            <br />
            PrimeSea is a private community where each member is authenticated
            through his unique non-fungible token (NFTs) running on the Polygon
            network. This website is only an interface allowing participants to
            purchase NFTs which represent a certificate of membership in
            PrimeSea. Users are entirely responsible for the safety and
            management of their own private digital wallets and validating all
            transactions and contracts generated by this website before
            approval. Furthermore, as the PrimeSea smart contract runs on the
            Polygon network, there is no ability to undo, reverse, or restore
            any transactions.
            <br />
            <br /> PrimeSea reserves itself the right to approve (or not) any
            and all PrimeSea membership applicants not only prior the primary
            NFT emission stage but also prior any future NFT transfer between an
            existing member and a new applicant. In that way, PrimeSea will
            always be responsible for approving new members to its community. In
            the case of a new applicant interested in buying the
            community&apos;s NFT from an existing member, the latter needs first
            to request his approval to PrimeSea through its proper communication
            channels. Finally, PrimeSea reserves itself the right to not
            disclose the criteria for approving (or not) new applicants into its
            private community. When approved, though, the new applicant will be
            formally informed and allowed to proceed with the purchase of the
            NFT membership certificate directly from PrimeSea or from an
            existing member.
            <br />
            <br />
            This website and its connected services are provided “as is” and “as
            available” without warranty of any kind. By using this website you
            are accepting sole responsibility for any and all transactions
            involving PrimeSea membership community.
            <br />
            <br />
            These Terms of Use (“Terms”) apply to your purchase, sale and
            display of PrimeSea non-fungible tokens (“PSNFT”). These Terms are
            entered into between you and W3BLOCK, INC (“Company,” “we,” or
            “us”). These Terms expressly incorporate any other documents
            referenced herein (such as our Privacy Policy) and govern your
            access to and use of this site www.primesea.io (the “Site”), as well
            as all content, functionality, and services offered on or through
            the Site, including the PSNFTs.
            <br />
            <br />
            <b>Reviewing and Accepting These Terms</b>
            <br />
            <br />
            Please read these Terms carefully, as they set out your rights and
            responsibilities when you use this Site to buy PSNFTs (the
            “Services”). When each PSNFT is sold for the first time, the
            agreement for sale is between the Company and the initial purchaser.
            If the initial purchaser decides to sell the PSNFT through this
            Site, then this Site serves only as a platform that facilitates
            transactions between a buyer and a seller and the Company is not a
            party to any agreement between such buyer and seller of PSNFTs or
            between any other users.
            <br />
            <br />
            All PSNFTs are stored on and accessible through the Polygon
            blockchain. As such, the Company does not maintain the PSNFTs on
            this Site and, aside from transferring control of the PSNFT to the
            initial purchaser of the PSNFT, the Company has no control over the
            transfer, storage, ownership or maintenance of the PSNFT.
            <br />
            <br />
            When you connect your cryptocurrency wallet to the Site using a
            trusted service provider such as MetaMask or Wallet Connect, you
            accept and agree to be bound and abide by these Terms and all of the
            terms incorporated herein by reference. By agreeing to these Terms,
            you hereby certify that you are at least 18 years of age. If you do
            not agree to these Terms, you must not access or use the Site.{' '}
            <br />
            <br />
            Please note that Section 13 contains an arbitration clause and class
            action waiver. By agreeing to these Terms, you agree to resolve all
            disputes through binding individual arbitration, which means that
            you waive any right to have the dispute decided by a judge or jury,
            and you waive any right to participate in collective action, whether
            that be a class action, class arbitration, or representative action.{' '}
            <br />
            <br />
            We reserve the right to change or modify these Terms at any time and
            in our sole discretion. You agree and understand that by accessing
            or using the Site following any change to these Terms, you are
            agreeing to the revised Terms and all of the terms incorporated
            therein by reference.
            <br />
            <br />
            Review the Terms each time you access the Site to ensure that you
            understand how the Terms apply to your activities on the Site.
            <br />
            <br />
            <b>1. Linking your Cryptocurrency Wallet</b>
            <br />
            <br />
            When you link your cryptocurrency wallet, you understand and agree
            that you are solely responsible for maintaining the security of your
            wallet and your control over any wallet-related authentication
            credentials, private or public cryptocurrency keys, non-fungible
            tokens or cryptocurrencies that are stored in or are accessible
            through your wallet. Any unauthorized access to your cryptocurrency
            wallet by third parties could result in the loss or theft of PSNFTs
            and/or funds held in your wallet and any associated wallets,
            including any linked financial information such as bank account(s)
            or credit card(s). We are not responsible for managing and
            maintaining the security of your cryptocurrency wallet nor for any
            unauthorized access to or use of your cryptocurrency wallet. If you
            notice any unauthorized or suspicious activity in your
            cryptocurrency wallet that seems to be related to this Site, please
            notify us immediately.
            <br />
            <br />
            <b>2. Ownership</b>
            <br />
            <br />
            Unless otherwise indicated in writing by us, the Site, all content,
            and all other materials contained therein, including, without
            limitation, our logos, and all designs, text, graphics, pictures,
            information, data, software, sound files, other files, and the
            selection and arrangement thereof (collectively, “Site Content”) are
            the proprietary property of W3BlOCK INC or our affiliates,
            licensors, or users, as applicable. The PRIMESEA logo and any
            PRIMESEA product or service names, logos, or slogans that may appear
            on the Site or elsewhere are trademarks of W3BLOCK INC or our
            affiliates, and may not be copied, imitated or used, in whole or in
            part, without our prior written permission.
            <br />
            <br />
            You may not use any Site Content or link to the Site without our
            prior written permission. You may not use framing techniques to
            enclose any Site Content without our express written consent. In
            addition, the look and feel of the Site Content, including without
            limitation, all page headers, custom graphics, button icons, and
            scripts constitute the service mark, trademark, or trade dress of
            PRIMESEA and may not be copied, imitated, or used, in whole or in
            part, without our prior written permission.
            <br />
            <br />
            <b>3. Terms of Sale</b>
            <br />
            <br />
            By placing an order on the Site, you agree that you are submitting a
            binding offer to purchase an PSNFT or other Service. If you are the
            initial purchaser of a PSNFT or you are purchasing a Service, then
            all amounts due are to be paid to W3BLOCK, INC. If you are not the
            initial purchaser of a PSNFT, then amounts may be paid to the-then
            holder of the PSNFT. You also acknowledge and agree that Company
            receives 10% of every subsequent sale of a PSNFT (“Royalty”). For
            example, if you are the initial purchaser, and you sell a PSNFT for
            $100 to a subsequent purchaser, $10 will automatically be
            transferred to Company and you will receive $90. Company has the
            right collect Royalties for PSNFT sales in perpetuity and may use
            those funds in any manner Company sees fit.
            <br />
            <br />
            <b className="underline">
              As such, if you sell a PSNFT on a third-party NFT marketplace, you
              agree to include a statement substantially similar to the
              following in the description of the NFT:
            </b>
            <br />
            <br />
            <i>“10% Royalty Applies. See W3BLOCK INC Terms for details.”</i>
            <br />
            <br />
            In addition, when you buy or sell a PSNFT on this Site, you agree to
            pay all applicable fees associated with the transaction and you
            authorize Us to automatically charge and collect such fees from your
            payment. We will always display a breakdown of any transaction or
            other fees prior to your purchase or sale of a PSNFT.
            <br />
            <br />
            No refunds are permitted except with respect to any statutory
            warranties or guarantees that cannot be excluded or limited by law.
            <br />
            <br />
            <b>4. Intellectual Property</b>
            <br />
            <br />
            Other than Site Content, all other trademarks, product names, and
            logos on the Site are the property of their respective owners and
            may not be copied, imitated, or used, in whole or in part, without
            the permission of the applicable trademark holder. Without limiting
            the foregoing, if you believe that third-party material hosted on
            the Site infringes your copyright or trademark rights, please file a
            notice of infringement by contacting the Designated Copyright Agent
            listed below.
            <br />
            <br />
            Your notice must contain the following information as required by
            the Digital Millennium Copyright Act (17 U.S.C. §512) (“DMCA”):
            <br />
            <br />
            <ul className="list-disc pl-20">
              <li>
                The full name and a physical or electronic signature of the
                person authorized to act on behalf of the copyright owner;
              </li>
              <br />
              <li>
                Identification of the copyrighted work claimed to have been
                infringed. If multiple copyrighted works are covered by your
                notice, you may provide a representative list of the copyrighted
                works that you claim have been infringed;
              </li>
              <br />
              <li>
                Reasonably sufficient detail to enable us to identify and locate
                the copyrighted work that is claimed to be infringing (e.g. a
                link to the page on the Site that contains the material);
              </li>
              <br />
              <li>
                A mailing address, telephone number, and email address where we
                can contact you;
              </li>
              <br />
              <li>
                A statement that you have a good faith belief that the disputed
                use of the copyrighted work is not authorized by the copyright
                owner, its agent, or the law; and
              </li>
              <br />
              <li>
                A statement made by you, under penalty of perjury, that the
                information in the notice is accurate and that you are the
                copyright owner or authorized to act on behalf of the copyright
                owner.
              </li>
            </ul>
            <br />
            Please submit your notice to the Designated Agent below:
            <br />
            <br />
            Email:{' '}
            <a href="mailto:ip@W3BLOCK.io" className="underline">
              ip@W3BLOCK.io
            </a>
            <b>
              {' '}
              (Subject Heading of Email: W3BLOCK DMCA Take Down Notification)
            </b>
            <br />
            <br />
            Once you provide us with an adequate notice as described above, we
            will respond expeditiously and take whatever action, in our sole
            discretion, that is deemed appropriate including removal of the
            disputed copyrighted work from the Site.
            <br />
            <br />
            Counter-Notice:
            <br />
            <br />
            If you believe that a DMCA notice of copyright infringement has been
            improperly submitted against you, you may submit a counter-notice to
            the Designated Agent with the following information required by the
            DMCA:
            <br />
            <br />
            <ul className="list-disc pl-20">
              <li>Your physical or electronic signature;</li>
              <br />
              <li>
                Identification of the copyrighted work that has been removed or
                to which access has been disabled including a link to the page
                on the Site that contained the material before it was removed or
                disabled;
              </li>
              <br />
              <li>
                A statement under penalty of perjury that you have a good faith
                belief that the copyrighted work was removed or disabled as a
                result of mistake or misidentification;
              </li>
              <br />
              <li>
                Your name, address, e-mail address, and telephone number; and
              </li>
              <br />
              <li>
                A statement that you (i) consent to the jurisdiction of the
                Federal District Court in the judicial district where your
                address is located if the address is in the United States, or
                the United District Court for the Southern District of New York
                (Manhattan) if your address is located outside of the United
                States, and (ii) accept service of process from the person who
                provided the DMCA notice of the alleged copyright infringement.
              </li>
            </ul>
            <br />
            Please submit your notice to the Designated Agent below:
            <br />
            <br />
            Email:{' '}
            <a href="mailto:ip@W3BLOCK.io" className="underline">
              ip@W3BLOCK.io
            </a>
            <b>
              {' '}
              (Subject Heading of Email: W3BLOCK DMCA Take Down Notification)
            </b>
            <br />
            <br />
            In the event that the Company receives a counter-notice in
            compliance with the above requirements, we will provide the person
            who submitted the DMCA copyright infringement notice with a copy of
            the counter-notice, informing them that the Company will replace the
            removed material in 10 business days from the date of the
            counter-notice unless the Company first receives notice from the
            person who submitted the DMCA copyright infringement notice that
            they have filed an action seeking a court order to restrain the
            allegedly infringing activity.
            <br />
            <br />
            PLEASE NOTE THAT W3BLOCK INC INTENDS TO COMPLY WITH ALL PROVISIONS
            OF THE DIGITAL MILLENNIUM COPYRIGHT ACT, BUT WILL NOT UNILATERALLY
            TAKE RESPONSIBILITY FOR POLICING AND REMOVING MATERIAL THOUGHT TO BE
            INFRINGING.
            <br />
            <br />
            We hereby grant you a limited, non-exclusive, non-transferable,
            revocable license to access and use the Site Content. In return, you
            agree not to engage, or assist, in any activity that violates any
            law, statute, ordinance, regulation, or sanctions program, including
            but not limited to the U.S. Department of Treasury&apos;s Office of
            Foreign Assets Control (“OFAC”), or that involves proceeds of any
            unlawful activity; not to engage in any other activity or behavior
            that poses a threat to W3BLOCK, INC, (e.g., by distributing a virus
            or other harmful code, or through unauthorized access to the Site or
            other users&apos; cryptocurrency wallets and not to interfere with
            other users&apos; access to or use of the Services.
            <br />
            <br />
            You also agree not to (1) distribute, publish, broadcast, reproduce,
            copy, retransmit, or publicly display any Site Content; (2) modify
            or create derivative works from the Site Content, or any portion
            thereof; (3) use any data mining, robots, or similar data gathering
            or extraction methods on the Site Content; (4) download any portion
            of the Site Content, other than for purposes of page caching, except
            as expressly permitted by us.
            <br />
            <br />
            With respect to the PSNFTs, each purchaser of a PSNFT is granted an
            exclusive, limited license to such PSNFT and its content to access,
            use, or store such PSNFT and its content solely for their personal,
            non-commercial purposes. PSNFTs are a limited-edition digital
            creation based upon content that may be trademarked and/or
            copyrighted by Company. Unless otherwise specified, your purchase of
            a PSNFT does not give you the right to publicly display, perform,
            distribute, sell or otherwise reproduce the PSNFT or its content for
            any commercial purpose. You further agree that you are not receiving
            any copyright interest in the PSNFT or its content, and indeed, you
            agree that Company may sell, license, modify, display, broadcast and
            create derivative works based upon your PSNFT or its content. Any
            commercial exploitation of the PSNFT could subject you to claims of
            copyright infringement. If you sell a PSNFT through the Site, you
            agree that you will not have any claims against us for any breach of
            these Terms by a purchaser. If you purchase a PSNFT on the Site, you
            hereby agree to hold us and the seller of such PSNFT harmless from
            and against any and all violations or breaches of these Terms.
            <br />
            <br />
            If you are unsure whether a contemplated use of the Site Content or
            a PSNFT and its content would violate these Terms, please contact us
            at support@w3block.io
            <br />
            <br />
            <b>5. Taxes</b>
            <br />
            <br />
            We are not responsible for determining the withholding, sales, use,
            value added, transfer or other taxes, together with any interest and
            penalties imposed with respect thereto (“Taxes”), that may apply to
            transactions on this Site. You agree that you are solely responsible
            for determining what, if any, Taxes apply to your transactions and
            to withhold, collect, report and remit the correct amounts of Taxes
            to the appropriate taxing authorities. Unless otherwise indicated on
            an applicable invoice, amounts due on this Site are exclusive of
            sale, use, value added or similar Taxes (“Sales Taxes”). This means
            that Sales Taxes become your sole responsibility. Upon our request,
            you agree to promptly provide a properly executed Internal Revenue
            Service Form W-9 or applicable Internal Revenue Service W-8 and any
            other tax form that is reasonably required by us so to comply with
            our tax reporting obligations.
            <br />
            <br />
            <b>6. Privacy</b>
            <br />
            <br />
            You acknowledge and agree to the collection, use, and disclosure of
            your personal information in accordance with our Privacy Policy,
            which is incorporated into these Terms.
            <br />
            <br />
            <b>7. Modifications</b>
            <br />
            <br />
            You agree and understand that we may modify part or all of this Site
            or the Services without notice, and that we may update these Terms
            and any other document incorporated by reference therein at any
            time.
            <br />
            <br />
            <b>8. Risks</b>
            <br />
            <br />
            Please note the following risks in accessing, purchasing, selling or
            using PSNFTs: The price and liquidity of blockchain assets,
            including PSNFTs, are extremely volatile and may be subject to large
            fluctuations. Fluctuations in the price of other digital assets
            could materially and adversely affect PSNFTs, which may also be
            subject to significant price volatility. Legislative and regulatory
            changes or actions at the state, federal, or international level may
            adversely affect the use, transfer, exchange, and value of PSNFTs.
            PSNFTs are not legal tender and are not backed by any government.
            Transactions in PSNFTs may be irreversible, and, accordingly, losses
            due to fraudulent or accidental transactions may not be recoverable.
            Some transactions in PSNFTs shall be deemed to be made when recorded
            on a public ledger, which is not necessarily the date or time that
            you initiated the transaction. The value of PSNFTs may be derived
            from the continued willingness of market participants to exchange
            fiat currency or digital assets for PSNFTs, which may result in the
            potential for permanent and total loss of value of a particular
            PSNFT should the market for that PSNFT disappear.
            <br />
            <br />
            You agree and understand that you are solely responsible for
            determining the nature, potential value, suitability, and
            appropriateness of these risks for yourself, and that we do not give
            advice or recommendations regarding PSNFTs, including the
            suitability and appropriateness of, and investment strategies for,
            PSNFTs. You agree and understand that you access and use this Site
            at your own risk; however, this brief statement does not disclose
            all of the risks associated with PSNFTs and other digital assets.
            You agree and understand that we will not be responsible for any
            communication failures, disruptions, errors, distortions or delays
            you may experience when using PSNFTs, however caused.
            <br />
            <br />
            <b>9. Disclaimers</b>
            <br />
            <br />
            EXCEPT AS EXPRESSLY PROVIDED TO THE CONTRARY IN A WRITING BY
            W3BLOCK, INC, THE SITE AND ANY SITE CONTENT CONTAINED THEREIN, AND
            ANY AND ALL PSNFTS LISTED THEREIN ARE PROVIDED ON AN “AS IS” AND “AS
            AVAILABLE” BASIS WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
            EITHER EXPRESS OR IMPLIED. PRIMESEA (AND ITS SUPPLIERS) MAKE NO
            WARRANTY THAT THE SITE WILL (1) MEET YOUR REQUIREMENTS; (2) BE
            AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS;
            OR (3) BE ACCURATE, RELIABLE, COMPLETE, LEGAL, OR SAFE.
            <br />
            <br />
            WE WILL NOT BE LIABLE FOR ANY LOSS OF ANY KIND FROM ANY ACTION TAKEN
            OR TAKEN IN RELIANCE ON MATERIAL OR INFORMATION, CONTAINED ON THE
            SITE. PRIMESEA DOES NOT REPRESENT OR WARRANT THAT SITE CONTENT IS
            ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE.
            <br />
            <br />
            WHILE WE ATTEMPT TO MAKE YOUR ACCESS TO AND USE OF THE SITE AND SITE
            CONTENT SAFE, WE CANNOT AND DO NOT REPRESENT OR WARRANT THAT THE
            SITE, SITE CONTENT, ANY PSNFTS LISTED ON OUR SITE OR OUR SERVERS ARE
            FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE CANNOT GUARANTEE THE
            SECURITY OF ANY DATA THAT YOU DISCLOSE ONLINE. YOU ACCEPT THE
            INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND DEALING ONLINE
            OVER THE INTERNET AND WILL NOT HOLD US RESPONSIBLE FOR ANY BREACH OF
            SECURITY UNLESS IT IS DUE TO OUR GROSS NEGLIGENCE.
            <br />
            <br />
            WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSS AND TAKE NO
            RESPONSIBILITY FOR, AND WILL NOT BE LIABLE TO YOU FOR, ANY USE OF
            PSNFTS INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES OR CLAIMS
            ARISING FROM: (A) USER ERROR SUCH AS FORGOTTEN PASSWORDS,
            INCORRECTLY CONSTRUCTED TRANSACTIONS, OR MISTYPED ADDRESSES; (B)
            SERVER FAILURE OR DATA LOSS; (C) CORRUPTED WALLET FILES; (D)
            UNAUTHORIZED ACCESS TO APPLICATIONS; (E) ANY UNAUTHORIZED THIRD
            PARTY ACTIVITIES, INCLUDING WITHOUT LIMITATION THE USE OF VIRUSES,
            PHISHING, BRUTE FORCING OR OTHER MEANS OF ATTACK AGAINST THE SITE OR
            PSNFTS.
            <br />
            <br />
            PSNFTS ARE INTANGIBLE DIGITAL ASSETS. THEY EXIST ONLY BY VIRTUE OF
            THE OWNERSHIP RECORD MAINTAINED IN THE POLYGON NETWORK. ANY TRANSFER
            OF TITLE THAT MIGHT OCCUR IN ANY UNIQUE DIGITAL ASSET OCCURS ON THE
            DECENTRALIZED LEDGER WITHIN THE POLYGON PLATFORM. WE DO NOT
            GUARANTEE THAT W3BLOCK, INC OR ANY W3BLOCK, INC PARTY CAN EFFECT THE
            TRANSFER OF TITLE OR RIGHT IN ANY PSNFT.
            <br />
            <br />
            We are not responsible for sustained casualties due to vulnerability
            or any kind of failure, abnormal behavior of software (e.g., wallet,
            smart contract), blockchains or any other features of the PSNFTs.
            W3BLOCK, INC is not responsible for casualties due to late report by
            developers or representatives (or no report at all) of any issues
            with the blockchain supporting PSNFTs including forks, technical
            node issues or any other issues having fund losses as a result.
            <br />
            <br />
            Nothing in these Terms shall exclude or limit liability of either
            party for fraud, death or bodily injury caused by negligence,
            violation of laws, or any other activity that cannot be limited or
            excluded by legitimate means.
            <br />
            <br />
            SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES
            IN CONTRACTS WITH CONSUMERS, SO THE ABOVE EXCLUSION MAY NOT APPLY TO
            YOU.
            <br />
            <br />
            <b>10. Limitation of Liability</b>
            <br />
            <br />
            TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL W3BLOCK,
            INC BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY
            INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE
            DAMAGES ARISING FROM THESE TERMS, THE SITE, SITE CONTENT, THE
            SERVICES OR THIRD PARTY SITES AND PRODUCTS, OR FOR ANY DAMAGES
            RELATED TO LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR
            ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, OR LOSS OF DATA,
            WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT,
            OR OTHERWISE, EVEN IF FORESEEABLE AND EVEN IF W3BLOCK, INC HAS BEEN
            ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF,
            THE SITE, SITE CONTENT, THE SERVICES OR THIRD PARTY SITES AND
            PRODUCTS ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY
            RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE
            OR LOSS OF DATA RESULTING THEREFROM.
            <br />
            <br />
            NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, IN NO
            EVENT SHALL THE MAXIMUM AGGREGATE LIABILITY OF PRIMESEA ARISING OUT
            OF OR IN ANY WAY RELATED TO THIS AGREEMENT, THE ACCESS TO AND USE OF
            THE SITE, SITE CONTENT, PSNFTS, OR ANY SERVICES PURCHASED ON THE
            SITE EXCEED THE GREATER OF (A) $100 OR (B) THE AMOUNT YOU HAVE PAID
            TO W3BLOCK, INC FOR THE SERVICES IN THE LAST TWELVE MONTHS OUT OF
            WHICH LIABILITY AROSE.
            <br />
            <br />
            <b>11. Indemnification</b>
            <br />
            <br />
            To the fullest extent permitted by applicable law, you agree to
            indemnify, defend and hold harmless W3BLOCK, INC, and our respective
            past, present and future employees, officers, directors,
            contractors, consultants, equity holders, suppliers, vendors,
            service providers, parent companies, subsidiaries, affiliates,
            agents, representatives, predecessors, successors and assigns
            (individually and collectively, the “W3BLOCK Parties”), from and
            against all actual or alleged third party claims, damages, awards,
            judgments, losses, liabilities, obligations, penalties, interest,
            fees, expenses (including, without limitation, attorneys’ fees and
            expenses) and costs (including, without limitation, court costs,
            costs of settlement and costs of pursuing indemnification and
            insurance), of every kind and nature whatsoever, whether known or
            unknown, foreseen or unforeseen, matured or unmatured, or suspected
            or unsuspected, in law or equity, whether in tort, contract or
            otherwise (collectively, “Claims”), including, but not limited to,
            damages to property or personal injury, that are caused by, arise
            out of or are related to (a) your use or misuse of the Site, Site
            Content, or PSNFTs, (c) your violation of these Terms, (c) your
            violation of the rights of a third party, including another user and
            (e) your failure to pay any Taxes or Sales Taxes in connection with
            your transactions on this Site or to provide us with a properly
            executed tax form described in Section 5. You agree to promptly
            notify us of any third party Claims and cooperate with the W3BLOCK
            Parties in defending such Claims. You further agree that the W3BLOCK
            Parties shall have control of the defense or settlement of any third
            party Claims. THIS INDEMNITY IS IN ADDITION TO, AND NOT IN LIEU OF,
            ANY OTHER INDEMNITIES SET FORTH IN A WRITTEN AGREEMENT BETWEEN YOU
            AND US.
            <br />
            <br />
            <b>12. Governing Law</b>
            <br />
            <br />
            These Terms of Use, your rights and obligations, and all actions
            contemplated by, arising out of or related to these Terms shall be
            governed by the laws of the State of Delaware, as if these Terms are
            a contract wholly entered into and wholly performed within the State
            of Delaware. YOU UNDERSTAND AND AGREE THAT YOUR USE OF THIS SITE AS
            CONTEMPLATED BY THESE TERMS SHALL BE DEEMED TO HAVE OCCURRED IN THE
            STATE OF DELAWARE AND BE SUBJECT TO THE INTERNAL LAWS OF THE STATE
            OF DELAWARE WITHOUT REGARD TO ITS CONFLICTS OF LAWS PROVISIONS.
            <br />
            <br />
            13. Arbitration Agreement & Waiver of Certain Rights, Including
            Class Actions
            <br />
            <br />
            PLEASE READ THIS SECTION CAREFULLY BECAUSE IT LIMITS CERTAIN RIGHTS,
            INCLUDING THE RIGHT TO MAINTAIN A COURT ACTION, THE RIGHT TO A JURY
            TRIAL, THE RIGHT TO PARTICIPATE IN ANY FORM OF CLASS OR
            REPRESENTATIVE CLAIM, THE RIGHT TO ENGAGE IN DISCOVERY EXCEPT AS
            PROVIDED IN AAA (AMERICAN ARBITRATION ASSOCIATION) RULES, AND THE
            RIGHT TO CERTAIN REMEDIES AND FORMS OF RELIEF. OTHER RIGHTS THAT YOU
            OR W3BLOCK WOULD HAVE IN COURT ALSO MAY NOT BE AVAILABLE IN
            ARBITRATION.
            <br />
            <br />
            <b>You Agree to Waive a Jury Trial</b>
            <br />
            <br />
            YOU AGREE TO RESOLVE ANY DISPUTES BETWEEN US THROUGH BINDING AND
            FINAL ARBITRATION INSTEAD OF THROUGH COURT PROCEEDINGS. YOU WAIVE
            YOUR RIGHT TO ANY JURY TRIAL OF ANY CLAIM. All controversies,
            claims, counterclaims, or other disputes arising between you and
            W3BLOCK relating to these Terms, our Site, W3BLOCK Item, PSNFTs, or
            any Orders shall be submitted for binding arbitration under the
            Rules of the American Arbitration Association (“AAA Rules”). The
            arbitration will be heard and determined by a single arbitrator. The
            arbitrator’s decision will be final and binding upon the parties and
            may be enforced in any court of competent jurisdiction. The parties
            agree that the arbitration will be kept confidential and that the
            existence of the proceeding and any element of it (including,
            without limitation, any pleadings, briefs or other documents
            submitted or exchanged and any testimony or other oral submissions
            and awards) will not be disclosed beyond the arbitration
            proceedings, except as may lawfully be required in judicial
            proceedings relating to the arbitration or by applicable disclosure
            rules and regulations of securities, regulatory authorities, or
            other governmental agencies.
            <br />
            <br />
            This arbitration agreement does not preclude you or W3BLOCK from
            seeking action by federal, state, or local government agencies. You
            and W3BLOCK may also bring qualifying claims in small claims court.
            In addition, you and W3BLOCK retain the right to apply to any court
            of competent jurisdiction for provisional relief, including
            pre-arbitral attachments or preliminary injunctions, and any such
            request shall not be deemed incompatible with these Terms, nor a
            waiver of the right to have disputes submitted to arbitration as
            provided in these Terms.
            <br />
            <br />
            <b>Arbitration Costs</b>
            <br />
            <br />
            If you demonstrate that the costs of arbitration will be prohibitive
            as compared to the costs of litigation, W3BLOCK will pay as much of
            the administrative costs and arbitrator fees required for the
            arbitration as the arbitrator deems necessary to prevent the cost of
            the arbitration from being prohibitive. In the final award, the
            arbitrator may apportion the costs of arbitration and the
            compensation of the arbitrator among the parties in such amounts as
            the arbitrator deems appropriate.
            <br />
            <br />
            <b>Class Action Waiver</b>
            <br />
            <br />
            YOU MAY NOT ACT AS A CLASS REPRESENTATIVE OR PRIVATE ATTORNEY
            GENERAL, NOR PARTICIPATE AS A CLASS MEMBER OF ANY CLASS CLAIMANTS
            WITH RESPECT TO ANY CLAIM. CLAIMS MAY NOT BE ARBITRATED ON A CLASS
            OR REPRESENTATIVE BASIS. You may only bring individual claims, and
            the arbitrator may only decide individual claims. The arbitrator may
            not consolidate or join the claims of other persons or parties who
            may be similarly situated.
            <br />
            <br />
            14. Severability: Arbitration Agreement
            <br />
            <br />
            Except as provided herein, if any part or parts of this Arbitration
            Agreement are found under the law to be invalid or unenforceable,
            then such specific part or parts shall be of no force and effect and
            shall be severed and the remainder of the Arbitration Agreement
            shall continue in full force and effect.
            <br />
            <br />
            <b>15. Survival of Agreement</b>
            <br />
            <br />
            This Arbitration Agreement will survive the termination of your
            relationship with W3BLOCK INC.
            <br />
            <br />
            <b>16. Modification</b>
            <br />
            <br />
            Notwithstanding any provision in these Terms to the contrary, we
            agree that if W3BLOCK INC makes any future material change to this
            Arbitration Agreement, you may reject that change within thirty (30)
            days of such change becoming effective by writing to us at the
            following address: support@W3BLOCK.io
            <br />
            <br />
            <b>17. Severability: Terms of Use</b>
            <br />
            <br />
            If any term, clause, or provision of these Terms is held invalid or
            unenforceable, then that term, clause, or provision shall be
            severable from these Terms and will not affect the validity or
            enforceability of any remaining part of that term, cause, or
            provision, or any other terms, clause, or provision of these Terms.
            <br />
            <br />
            <b>18. Entire Agreement</b>
            <br />
            <br />
            These Terms comprise the entire agreement between you and us
            relating to your access to and use of the Site, Site Content and any
            PSNFTs you have purchased, and supersede any and all prior
            discussions agreements, and understandings of any kind. Except as
            otherwise provided herein, these Terms are intended solely for the
            benefit of the parties and are not intended to confer third party
            beneficiary rights upon any other person or entity.
          </p>
        </div>
      </div>
      <div className="background-about">
        <Footer className="bg-transparent mt-8 pt-[240px]" />
      </div>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? '')),
    },
  };
};

export default Terms;
